version: '3.7'
x-base:
  &base
  restart: always
  logging:
    driver: json-file
    options:
      max-size: 1m
      max-file: 1
services:
  server:
    <<: *base
    build:
      context: .
      dockerfile: server/src/Server.Host/app.dockerfile
    image: exta-server
    container_name: exta-server
    ports:
      - '8101:5000'
    depends_on:
      - db
  db:
    <<: *base
    image: registry.annium.com/postgres:15
    container_name: exta-db
    ports:
      - 8191:5432
    volumes:
      - db:/var/lib/postgresql/data
    env_file: run/db/db.env
  site:
    <<: *base
    build:
      context: .
      dockerfile: site/src/Site/app.dockerfile
    image: exta-site
    container_name: exta-site
    ports:
      - '8100:80'
    depends_on:
      - db
volumes:
  db:
